title: Aastha's thoughts, ideas, stories, codes
author: Aastha Varma
email: aastha.code@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Foodie, Nerd, Star wars die hard fan | Student NITRourkela | AWS

# social links
twitter_username: AskAasthaVarma # DO NOT include the @ character, or else the build will fail!
github_username:  aasthavar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
